{
  "total_texts": 300,
  "successful_processing": 293,
  "regex_errors": [
    {
      "text_index": 73,
      "text": "Tom was not allowed to leave.",
      "label": "Unknown",
      "error": "invalid group reference 3 at position 1",
      "error_type": "PatternError",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/mansigahlawat/Desktop/person_b/debug_benchmark.py\", line 64, in debug_pipeline_processing\n    result = self.pipeline.process_text(text)\n  File \"/Users/mansigahlawat/Desktop/person_b/pipeline.py\", line 56, in process_text\n    paraphrases = self.paraphraser.generate_paraphrases(sent_text)\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 49, in generate_paraphrases\n    paraphrases.append(self._voice_paraphrase(text))\n                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 78, in _voice_paraphrase\n    result = re.sub(r'\\b(was|were|is|are)\\s+([\\w]+ed)\\s+by\\b', r'\\3 \\2', text)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 208, in sub\n    return _compile(pattern, flags).sub(repl, string, count)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 377, in _compile_template\n    return _sre.template(pattern, _parser.parse_template(repl, pattern))\n                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1070, in parse_template\n    addgroup(int(this[1:]), len(this) - 1)\n    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1015, in addgroup\n    raise s.error(\"invalid group reference %d\" % index, pos)\nre.PatternError: invalid group reference 3 at position 1\n"
    },
    {
      "text_index": 113,
      "text": "It's never happened before.",
      "label": "Unknown",
      "error": "invalid group reference 3 at position 1",
      "error_type": "PatternError",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/mansigahlawat/Desktop/person_b/debug_benchmark.py\", line 64, in debug_pipeline_processing\n    result = self.pipeline.process_text(text)\n  File \"/Users/mansigahlawat/Desktop/person_b/pipeline.py\", line 56, in process_text\n    paraphrases = self.paraphraser.generate_paraphrases(sent_text)\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 49, in generate_paraphrases\n    paraphrases.append(self._voice_paraphrase(text))\n                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 78, in _voice_paraphrase\n    result = re.sub(r'\\b(was|were|is|are)\\s+([\\w]+ed)\\s+by\\b', r'\\3 \\2', text)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 208, in sub\n    return _compile(pattern, flags).sub(repl, string, count)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 377, in _compile_template\n    return _sre.template(pattern, _parser.parse_template(repl, pattern))\n                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1070, in parse_template\n    addgroup(int(this[1:]), len(this) - 1)\n    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1015, in addgroup\n    raise s.error(\"invalid group reference %d\" % index, pos)\nre.PatternError: invalid group reference 3 at position 1\n"
    },
    {
      "text_index": 185,
      "text": "Why don't we get rid of this mess?",
      "label": "Unknown",
      "error": "invalid group reference 3 at position 1",
      "error_type": "PatternError",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/mansigahlawat/Desktop/person_b/debug_benchmark.py\", line 64, in debug_pipeline_processing\n    result = self.pipeline.process_text(text)\n  File \"/Users/mansigahlawat/Desktop/person_b/pipeline.py\", line 56, in process_text\n    paraphrases = self.paraphraser.generate_paraphrases(sent_text)\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 49, in generate_paraphrases\n    paraphrases.append(self._voice_paraphrase(text))\n                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 78, in _voice_paraphrase\n    result = re.sub(r'\\b(was|were|is|are)\\s+([\\w]+ed)\\s+by\\b', r'\\3 \\2', text)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 208, in sub\n    return _compile(pattern, flags).sub(repl, string, count)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 377, in _compile_template\n    return _sre.template(pattern, _parser.parse_template(repl, pattern))\n                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1070, in parse_template\n    addgroup(int(this[1:]), len(this) - 1)\n    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1015, in addgroup\n    raise s.error(\"invalid group reference %d\" % index, pos)\nre.PatternError: invalid group reference 3 at position 1\n"
    },
    {
      "text_index": 214,
      "text": "Were you born there?",
      "label": "Unknown",
      "error": "invalid group reference 3 at position 1",
      "error_type": "PatternError",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/mansigahlawat/Desktop/person_b/debug_benchmark.py\", line 64, in debug_pipeline_processing\n    result = self.pipeline.process_text(text)\n  File \"/Users/mansigahlawat/Desktop/person_b/pipeline.py\", line 56, in process_text\n    paraphrases = self.paraphraser.generate_paraphrases(sent_text)\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 49, in generate_paraphrases\n    paraphrases.append(self._voice_paraphrase(text))\n                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 78, in _voice_paraphrase\n    result = re.sub(r'\\b(was|were|is|are)\\s+([\\w]+ed)\\s+by\\b', r'\\3 \\2', text)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 208, in sub\n    return _compile(pattern, flags).sub(repl, string, count)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 377, in _compile_template\n    return _sre.template(pattern, _parser.parse_template(repl, pattern))\n                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1070, in parse_template\n    addgroup(int(this[1:]), len(this) - 1)\n    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1015, in addgroup\n    raise s.error(\"invalid group reference %d\" % index, pos)\nre.PatternError: invalid group reference 3 at position 1\n"
    },
    {
      "text_index": 225,
      "text": "The publication of the article was timed to the birthday of the professor.",
      "label": "Unknown",
      "error": "invalid group reference 3 at position 1",
      "error_type": "PatternError",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/mansigahlawat/Desktop/person_b/debug_benchmark.py\", line 64, in debug_pipeline_processing\n    result = self.pipeline.process_text(text)\n  File \"/Users/mansigahlawat/Desktop/person_b/pipeline.py\", line 56, in process_text\n    paraphrases = self.paraphraser.generate_paraphrases(sent_text)\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 49, in generate_paraphrases\n    paraphrases.append(self._voice_paraphrase(text))\n                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 78, in _voice_paraphrase\n    result = re.sub(r'\\b(was|were|is|are)\\s+([\\w]+ed)\\s+by\\b', r'\\3 \\2', text)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 208, in sub\n    return _compile(pattern, flags).sub(repl, string, count)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 377, in _compile_template\n    return _sre.template(pattern, _parser.parse_template(repl, pattern))\n                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1070, in parse_template\n    addgroup(int(this[1:]), len(this) - 1)\n    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1015, in addgroup\n    raise s.error(\"invalid group reference %d\" % index, pos)\nre.PatternError: invalid group reference 3 at position 1\n"
    },
    {
      "text_index": 254,
      "text": "I was bitten by a spider.",
      "label": "Unknown",
      "error": "invalid group reference 3 at position 1",
      "error_type": "PatternError",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/mansigahlawat/Desktop/person_b/debug_benchmark.py\", line 64, in debug_pipeline_processing\n    result = self.pipeline.process_text(text)\n  File \"/Users/mansigahlawat/Desktop/person_b/pipeline.py\", line 56, in process_text\n    paraphrases = self.paraphraser.generate_paraphrases(sent_text)\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 49, in generate_paraphrases\n    paraphrases.append(self._voice_paraphrase(text))\n                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 78, in _voice_paraphrase\n    result = re.sub(r'\\b(was|were|is|are)\\s+([\\w]+ed)\\s+by\\b', r'\\3 \\2', text)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 208, in sub\n    return _compile(pattern, flags).sub(repl, string, count)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 377, in _compile_template\n    return _sre.template(pattern, _parser.parse_template(repl, pattern))\n                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1070, in parse_template\n    addgroup(int(this[1:]), len(this) - 1)\n    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1015, in addgroup\n    raise s.error(\"invalid group reference %d\" % index, pos)\nre.PatternError: invalid group reference 3 at position 1\n"
    },
    {
      "text_index": 293,
      "text": "Tom was born here.",
      "label": "Unknown",
      "error": "invalid group reference 3 at position 1",
      "error_type": "PatternError",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/mansigahlawat/Desktop/person_b/debug_benchmark.py\", line 64, in debug_pipeline_processing\n    result = self.pipeline.process_text(text)\n  File \"/Users/mansigahlawat/Desktop/person_b/pipeline.py\", line 56, in process_text\n    paraphrases = self.paraphraser.generate_paraphrases(sent_text)\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 49, in generate_paraphrases\n    paraphrases.append(self._voice_paraphrase(text))\n                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"/Users/mansigahlawat/Desktop/person_b/paraphrase.py\", line 78, in _voice_paraphrase\n    result = re.sub(r'\\b(was|were|is|are)\\s+([\\w]+ed)\\s+by\\b', r'\\3 \\2', text)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 208, in sub\n    return _compile(pattern, flags).sub(repl, string, count)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py\", line 377, in _compile_template\n    return _sre.template(pattern, _parser.parse_template(repl, pattern))\n                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1070, in parse_template\n    addgroup(int(this[1:]), len(this) - 1)\n    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/_parser.py\", line 1015, in addgroup\n    raise s.error(\"invalid group reference %d\" % index, pos)\nre.PatternError: invalid group reference 3 at position 1\n"
    }
  ],
  "other_errors": [],
  "problematic_texts": []
}